# docker-compose.yaml
services:
  ds3x-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: ds3x-bigquery
    #volumes:
      #- .:/app
      #- ./AccessKey:/app/AccessKey
      #- ./download:/app/download
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/AccessKey/SA-william_tomazeto.json
